# Generated by Django 3.0.2 on 2020-05-09 18:56

from django.db import migrations, models

def convert_interest(apps, schema_editor):
    EventInterest = apps.get_model('api', 'EventInterest')
    for interest in EventInterest.objects.all():
        interest.status = "0"
        interest.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_eventinterest'),
    ]

    operations = [
        migrations.RunPython(convert_interest),
        migrations.AlterField(
            model_name='eventinterest',
            name='status',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Going'), (2, 'Interested')], default=0),
        ),
    ]
