# Generated by Django 3.0.2 on 2020-04-22 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200210_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.IntegerField()),
                ('street_name', models.TextField()),
                ('street_type', models.TextField()),
                ('street_direction', models.TextField()),
                ('address_type', models.TextField()),
                ('address_type_id', models.TextField()),
                ('minor_municipality', models.TextField()),
                ('major_municipality', models.TextField()),
                ('governing_district', models.TextField()),
                ('postal_area', models.TextField()),
                ('country', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='api.Address'),
        ),
    ]
