# Generated by Django 3.0.2 on 2020-04-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200422_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.TextField(default="Barbecue, bitches. It's what we got"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='minor_municipality',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_direction',
            field=models.TextField(blank=True),
        ),
    ]
